### PR TITLE
29 render events in chronological order

### PR DESCRIPTION
**Pull request by craigsapp**
Two small changes: (1) add range option to slider on timeline (2) correct corpus link in index.md.

### CODE REVIEW

**Comment by lilydemet** [comment]
Will you change the feature property from "first_publication_year" to "premiere_date" and ensure the sorting still works?

**Comment by craigsapp** [comment]
Yes, I will do that now (to this same branch/PR I am presuming).

**Comment by craigsapp** [comment]
Commit https://github.com/polyrhythm-project/polyrhythm-maps/commit/19dc4972c7a92118b89c22b57d3dc9d4d7931889 changes the slider to display premier year, and sorting is working (see issue #40 for implementation notes).

**Comment by lilydemet** [comment]
awesome!! thanks

**Pull request merged**
